/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package PersonaService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Persona service. Represents a row in the &quot;persona&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>PersonaService.model.impl.PersonaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>PersonaService.model.impl.PersonaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Persona
 * @generated
 */
@ProviderType
public interface PersonaModel extends BaseModel<Persona> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persona model instance should use the {@link Persona} interface instead.
	 */

	/**
	 * Returns the primary key of this persona.
	 *
	 * @return the primary key of this persona
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persona.
	 *
	 * @param primaryKey the primary key of this persona
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_persona of this persona.
	 *
	 * @return the id_persona of this persona
	 */
	public long getId_persona();

	/**
	 * Sets the id_persona of this persona.
	 *
	 * @param id_persona the id_persona of this persona
	 */
	public void setId_persona(long id_persona);

	/**
	 * Returns the frist name of this persona.
	 *
	 * @return the frist name of this persona
	 */
	@AutoEscape
	public String getFristName();

	/**
	 * Sets the frist name of this persona.
	 *
	 * @param fristName the frist name of this persona
	 */
	public void setFristName(String fristName);

	/**
	 * Returns the last name of this persona.
	 *
	 * @return the last name of this persona
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this persona.
	 *
	 * @param lastName the last name of this persona
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the age of this persona.
	 *
	 * @return the age of this persona
	 */
	public int getAge();

	/**
	 * Sets the age of this persona.
	 *
	 * @param age the age of this persona
	 */
	public void setAge(int age);

}