/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.az.dev.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Cutomer service. Represents a row in the &quot;customer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.az.dev.model.impl.CutomerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.az.dev.model.impl.CutomerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Cutomer
 * @generated
 */
@ProviderType
public interface CutomerModel extends BaseModel<Cutomer> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cutomer model instance should use the {@link Cutomer} interface instead.
	 */

	/**
	 * Returns the primary key of this cutomer.
	 *
	 * @return the primary key of this cutomer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cutomer.
	 *
	 * @param primaryKey the primary key of this cutomer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_customer of this cutomer.
	 *
	 * @return the id_customer of this cutomer
	 */
	public long getId_customer();

	/**
	 * Sets the id_customer of this cutomer.
	 *
	 * @param id_customer the id_customer of this cutomer
	 */
	public void setId_customer(long id_customer);

	/**
	 * Returns the name of this cutomer.
	 *
	 * @return the name of this cutomer
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cutomer.
	 *
	 * @param name the name of this cutomer
	 */
	public void setName(String name);

	/**
	 * Returns the age of this cutomer.
	 *
	 * @return the age of this cutomer
	 */
	@AutoEscape
	public String getAge();

	/**
	 * Sets the age of this cutomer.
	 *
	 * @param age the age of this cutomer
	 */
	public void setAge(String age);

	/**
	 * Returns the email of this cutomer.
	 *
	 * @return the email of this cutomer
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this cutomer.
	 *
	 * @param email the email of this cutomer
	 */
	public void setEmail(String email);

}